// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/downloads/domain/usecases/clear_all_downloads_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:audio_service/audio_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tilawa/features/downloads/domain/entities/download_item.dart'
    as _i5;
import 'package:tilawa/features/downloads/domain/repositories/downloads_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMediaItem_0 extends _i1.SmartFake implements _i2.MediaItem {
  _FakeMediaItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsRepository extends _i1.Mock
    implements _i3.DownloadsRepository {
  MockDownloadsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.DownloadItem> get downloadUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#downloadUpdates),
            returnValue: _i4.Stream<_i5.DownloadItem>.empty(),
          )
          as _i4.Stream<_i5.DownloadItem>);

  @override
  _i4.Future<void> addDownload(_i5.DownloadItem? downloadItem) =>
      (super.noSuchMethod(
            Invocation.method(#addDownload, [downloadItem]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDownload(_i5.DownloadItem? downloadItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateDownload, [downloadItem]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownload, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDownloadProgress(
    String? id,
    _i5.DownloadStatus? status,
    double? progress,
    int? downloadedSize,
    int? fileSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDownloadProgress, [
              id,
              status,
              progress,
              downloadedSize,
              fileSize,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startDownload(
    String? url, {
    required String? title,
    bool? showNotification = true,
    required String? surahTitle,
    required String? reciterName,
    required int? reciterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startDownload,
              [url],
              {
                #title: title,
                #showNotification: showNotification,
                #surahTitle: surahTitle,
                #reciterName: reciterName,
                #reciterId: reciterId,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pauseDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#pauseDownload, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumeDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#resumeDownload, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> retryDownload(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryDownload, [downloadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSurahDownloaded(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#isSurahDownloaded, [url, reciterName]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isSurahDownloading(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#isSurahDownloading, [url, reciterName]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getDownloadedFilePath(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedFilePath, [url, reciterName]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Stream<_i5.DownloadItem> getDownloadProgress(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadProgress, [id]),
            returnValue: _i4.Stream<_i5.DownloadItem>.empty(),
          )
          as _i4.Stream<_i5.DownloadItem>);

  @override
  _i4.Future<void> startDownloadBatch(
    List<({int reciterId, String reciterName, String surahTitle, String url})>?
    items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startDownloadBatch, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelDownloadsForReciter(String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownloadsForReciter, [reciterName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDownloadsForReciter(String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadsForReciter, [reciterName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, Map<String, List<_i5.DownloadItem>>>>
  getDownloadsByReciter() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsByReciter, []),
            returnValue:
                _i4.Future<
                  Map<String, Map<String, List<_i5.DownloadItem>>>
                >.value(<String, Map<String, List<_i5.DownloadItem>>>{}),
          )
          as _i4.Future<Map<String, Map<String, List<_i5.DownloadItem>>>>);

  @override
  _i4.Future<List<_i5.DownloadItem>> getDownloadsForReciter(
    String? reciterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsForReciter, [reciterName]),
            returnValue: _i4.Future<List<_i5.DownloadItem>>.value(
              <_i5.DownloadItem>[],
            ),
          )
          as _i4.Future<List<_i5.DownloadItem>>);

  @override
  _i4.Future<_i5.DownloadItem?> getDownloadItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadItem, [id]),
            returnValue: _i4.Future<_i5.DownloadItem?>.value(),
          )
          as _i4.Future<_i5.DownloadItem?>);

  @override
  _i4.Future<List<_i5.DownloadItem>> getValidCompletedDownloads(
    String? reciterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getValidCompletedDownloads, [reciterName]),
            returnValue: _i4.Future<List<_i5.DownloadItem>>.value(
              <_i5.DownloadItem>[],
            ),
          )
          as _i4.Future<List<_i5.DownloadItem>>);

  @override
  _i4.Future<bool> validateDownloadedFile(_i5.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#validateDownloadedFile, [download]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i2.MediaItem createMediaItemFromDownload(_i5.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#createMediaItemFromDownload, [download]),
            returnValue: _FakeMediaItem_0(
              this,
              Invocation.method(#createMediaItemFromDownload, [download]),
            ),
          )
          as _i2.MediaItem);

  @override
  List<_i2.MediaItem> createMediaItemsFromDownloads(
    List<_i5.DownloadItem>? downloads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMediaItemsFromDownloads, [downloads]),
            returnValue: <_i2.MediaItem>[],
          )
          as List<_i2.MediaItem>);

  @override
  _i4.Future<int> getTotalDownloadsSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalDownloadsSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> clearAllDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllDownloads, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumePendingDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#resumePendingDownloads, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
