// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/premium/data/repositories/premium_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tilawa/features/premium/data/datasources/premium_local_datasource.dart'
    as _i3;
import 'package:tilawa/features/premium/data/datasources/premium_remote_datasource.dart'
    as _i5;
import 'package:tilawa/features/premium/domain/entities/premium_status.dart'
    as _i2;
import 'package:tilawa/features/premium/domain/entities/subscription_plan.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePremiumStatus_0 extends _i1.SmartFake implements _i2.PremiumStatus {
  _FakePremiumStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PremiumLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremiumLocalDataSource extends _i1.Mock
    implements _i3.PremiumLocalDataSource {
  MockPremiumLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PremiumStatus> getPremiumStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getPremiumStatus, []),
            returnValue: _i4.Future<_i2.PremiumStatus>.value(
              _FakePremiumStatus_0(
                this,
                Invocation.method(#getPremiumStatus, []),
              ),
            ),
          )
          as _i4.Future<_i2.PremiumStatus>);

  @override
  _i4.Future<void> savePremiumStatus(_i2.PremiumStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#savePremiumStatus, [status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearPremiumStatus() =>
      (super.noSuchMethod(
            Invocation.method(#clearPremiumStatus, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PremiumRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremiumRemoteDataSource extends _i1.Mock
    implements _i5.PremiumRemoteDataSource {
  MockPremiumRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PremiumStatus?> getPremiumStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getPremiumStatus, []),
            returnValue: _i4.Future<_i2.PremiumStatus?>.value(),
          )
          as _i4.Future<_i2.PremiumStatus?>);

  @override
  _i4.Future<void> updatePremiumStatus(_i2.PremiumStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updatePremiumStatus, [status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.SubscriptionPlan>> getAvailablePlans() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePlans, []),
            returnValue: _i4.Future<List<_i6.SubscriptionPlan>>.value(
              <_i6.SubscriptionPlan>[],
            ),
          )
          as _i4.Future<List<_i6.SubscriptionPlan>>);

  @override
  _i4.Future<bool> purchaseSubscription(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseSubscription, [planId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancelSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> restoreSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSubscription, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
