// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/downloads/data/services/flutter_downloader_wrapper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_downloader/flutter_downloader.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tilawa/features/downloads/data/services/flutter_downloader_wrapper.dart'
    as _i2;
import 'package:tilawa/features/downloads/data/services/helpers/download_file_helper.dart'
    as _i5;
import 'package:tilawa/features/downloads/data/services/helpers/download_isolate_manager.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FlutterDownloaderWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterDownloaderWrapper extends _i1.Mock
    implements _i2.FlutterDownloaderWrapper {
  MockFlutterDownloaderWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize({bool? debug = true, bool? ignoreSsl = false}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #debug: debug,
              #ignoreSsl: ignoreSsl,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> registerCallback(
    _i4.DownloadCallback? callback, {
    int? step = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerCallback, [callback], {#step: step}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> enqueue({
    required String? url,
    required String? savedDir,
    required String? fileName,
    Map<String, String>? headers,
    bool? showNotification = false,
    bool? openFileFromNotification = true,
    bool? requiresStorageNotLow = true,
    bool? saveInPublicStorage = false,
    String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #url: url,
              #savedDir: savedDir,
              #fileName: fileName,
              #headers: headers,
              #showNotification: showNotification,
              #openFileFromNotification: openFileFromNotification,
              #requiresStorageNotLow: requiresStorageNotLow,
              #saveInPublicStorage: saveInPublicStorage,
              #title: title,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> cancel({required String? taskId}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [], {#taskId: taskId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause({required String? taskId}) =>
      (super.noSuchMethod(
            Invocation.method(#pause, [], {#taskId: taskId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume({required String? taskId}) =>
      (super.noSuchMethod(
            Invocation.method(#resume, [], {#taskId: taskId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> retry({required String? taskId}) =>
      (super.noSuchMethod(
            Invocation.method(#retry, [], {#taskId: taskId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> remove({
    required String? taskId,
    bool? shouldDeleteContent = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [], {
              #taskId: taskId,
              #shouldDeleteContent: shouldDeleteContent,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DownloadTask>?> loadTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, []),
            returnValue: _i3.Future<List<_i4.DownloadTask>?>.value(),
          )
          as _i3.Future<List<_i4.DownloadTask>?>);

  @override
  _i3.Future<List<_i4.DownloadTask>?> loadTasksWithRawQuery({
    required String? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadTasksWithRawQuery, [], {#query: query}),
            returnValue: _i3.Future<List<_i4.DownloadTask>?>.value(),
          )
          as _i3.Future<List<_i4.DownloadTask>?>);
}

/// A class which mocks [DownloadFileHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadFileHelper extends _i1.Mock
    implements _i5.DownloadFileHelper {
  MockDownloadFileHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getDirectoryName(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectoryName, [filePath]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getDirectoryName, [filePath]),
            ),
          )
          as String);

  @override
  String getFileName(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getFileName, [filePath]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getFileName, [filePath]),
            ),
          )
          as String);

  @override
  bool ensureDirectoryExists(String? savedDir) =>
      (super.noSuchMethod(
            Invocation.method(#ensureDirectoryExists, [savedDir]),
            returnValue: false,
          )
          as bool);

  @override
  bool isFileExists(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#isFileExists, [filePath]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [DownloadIsolateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadIsolateManager extends _i1.Mock
    implements _i7.DownloadIsolateManager {
  MockDownloadIsolateManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<(String, _i4.DownloadTaskStatus, int)> get updateStream =>
      (super.noSuchMethod(
            Invocation.getter(#updateStream),
            returnValue:
                _i3.Stream<(String, _i4.DownloadTaskStatus, int)>.empty(),
          )
          as _i3.Stream<(String, _i4.DownloadTaskStatus, int)>);

  @override
  void registerPort() => super.noSuchMethod(
    Invocation.method(#registerPort, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
