name: muzakri
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "3.9.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # audioplayers: ^0.19.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  # excel: 2.0.0-null-safety-3
  file_picker: ^10.3.3
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  get_it: ^8.0.0
  flutter_screenutil: ^5.9.3

  # Audio Packages
  # just_audio_background:
  audio_video_progress_bar: ^2.0.3
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  rxdart: ^0.28.0

  provider: ^6.1.2
  equatable: ^2.0.5
  go_router: ^16.2.4
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  hugeicons: ^1.1.0
  fluentui_system_icons: ^1.1.273
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  google_sign_in: ^7.2.0
  injectable: ^2.5.2
  firebase_crashlytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/Book.xlsx

  fonts:
    - family: TheSans
      fonts:
        - asset: assets/fonts/TheSansPlain.otf
