// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/audio_player/presentation/bloc/audio_player_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dartz_plus/src/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tilawa/core/entities/audio.dart' as _i8;
import 'package:tilawa/core/errors/failures.dart' as _i5;
import 'package:tilawa/features/audio_player/domain/entities/audio_modes.dart'
    as _i7;
import 'package:tilawa/features/audio_player/domain/usecases/audio_player_usecases.dart'
    as _i2;
import 'package:tilawa/features/audio_player/domain/usecases/get_audio_streams_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlayAudioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayAudioUseCase extends _i1.Mock implements _i2.PlayAudioUseCase {
  MockPlayAudioUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [PauseAudioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPauseAudioUseCase extends _i1.Mock implements _i2.PauseAudioUseCase {
  MockPauseAudioUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [StopAudioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopAudioUseCase extends _i1.Mock implements _i2.StopAudioUseCase {
  MockStopAudioUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SeekToUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeekToUseCase extends _i1.Mock implements _i2.SeekToUseCase {
  MockSeekToUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#call, [position]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [position]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SetVolumeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetVolumeUseCase extends _i1.Mock implements _i2.SetVolumeUseCase {
  MockSetVolumeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#call, [volume]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [volume]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SetPlaybackSpeedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetPlaybackSpeedUseCase extends _i1.Mock
    implements _i2.SetPlaybackSpeedUseCase {
  MockSetPlaybackSpeedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#call, [speed]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [speed]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SetRepeatModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetRepeatModeUseCase extends _i1.Mock
    implements _i2.SetRepeatModeUseCase {
  MockSetRepeatModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i7.AudioRepeatMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [mode]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [mode]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SetShuffleModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetShuffleModeUseCase extends _i1.Mock
    implements _i2.SetShuffleModeUseCase {
  MockSetShuffleModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i7.AudioShuffleMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [mode]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [mode]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SkipToNextUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkipToNextUseCase extends _i1.Mock implements _i2.SkipToNextUseCase {
  MockSkipToNextUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SkipToPreviousUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkipToPreviousUseCase extends _i1.Mock
    implements _i2.SkipToPreviousUseCase {
  MockSkipToPreviousUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [SkipToQueueItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkipToQueueItemUseCase extends _i1.Mock
    implements _i2.SkipToQueueItemUseCase {
  MockSkipToQueueItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#call, [index]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [index]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [PlayFromQueueUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayFromQueueUseCase extends _i1.Mock
    implements _i2.PlayFromQueueUseCase {
  MockPlayFromQueueUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    List<_i8.AudioEntity>? queue,
    int? index,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [queue, index]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [queue, index]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [UpdateQueueUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateQueueUseCase extends _i1.Mock
    implements _i2.UpdateQueueUseCase {
  MockUpdateQueueUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    List<_i8.AudioEntity>? queue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [queue]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [queue]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [AddQueueItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddQueueItemUseCase extends _i1.Mock
    implements _i2.AddQueueItemUseCase {
  MockAddQueueItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i8.AudioEntity? audio) =>
      (super.noSuchMethod(
            Invocation.method(#call, [audio]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [audio]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [RemoveQueueItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveQueueItemUseCase extends _i1.Mock
    implements _i2.RemoveQueueItemUseCase {
  MockRemoveQueueItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i8.AudioEntity? audio) =>
      (super.noSuchMethod(
            Invocation.method(#call, [audio]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [audio]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [MoveQueueItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoveQueueItemUseCase extends _i1.Mock
    implements _i2.MoveQueueItemUseCase {
  MockMoveQueueItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    int? currentIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [currentIndex, newIndex]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [currentIndex, newIndex]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [LoadAudioPlayerDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadAudioPlayerDataUseCase extends _i1.Mock
    implements _i2.LoadAudioPlayerDataUseCase {
  MockLoadAudioPlayerDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call({
    bool? restorePlayback = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#restorePlayback: restorePlayback}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [], {
                  #restorePlayback: restorePlayback,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [GetAudioStreamsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAudioStreamsUseCase extends _i1.Mock
    implements _i9.GetAudioStreamsUseCase {
  MockGetAudioStreamsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i8.PlaybackStateEntity> get playbackState =>
      (super.noSuchMethod(
            Invocation.getter(#playbackState),
            returnValue: _i3.Stream<_i8.PlaybackStateEntity>.empty(),
          )
          as _i3.Stream<_i8.PlaybackStateEntity>);

  @override
  _i3.Stream<_i8.AudioEntity?> get currentAudio =>
      (super.noSuchMethod(
            Invocation.getter(#currentAudio),
            returnValue: _i3.Stream<_i8.AudioEntity?>.empty(),
          )
          as _i3.Stream<_i8.AudioEntity?>);

  @override
  _i3.Stream<List<_i8.AudioEntity>> get queue =>
      (super.noSuchMethod(
            Invocation.getter(#queue),
            returnValue: _i3.Stream<List<_i8.AudioEntity>>.empty(),
          )
          as _i3.Stream<List<_i8.AudioEntity>>);

  @override
  _i3.Stream<double> get volume =>
      (super.noSuchMethod(
            Invocation.getter(#volume),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  _i3.Stream<double> get speed =>
      (super.noSuchMethod(
            Invocation.getter(#speed),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  _i3.Stream<Duration> get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _i3.Stream<Duration>.empty(),
          )
          as _i3.Stream<Duration>);
}
