export enum SessionLifecycleStatus {
  Draft = 'draft',
  PendingPayment = 'pending_payment',
  Scheduled = 'scheduled',
  Confirmed = 'confirmed',
  InProgress = 'in_progress',
  Rescheduled = 'rescheduled',
  CancelledByStudent = 'cancelled_by_student',
  CancelledByTeacher = 'cancelled_by_teacher',
  CancelledByAdmin = 'cancelled_by_admin',
  TeacherNoShow = 'teacher_no_show',
  StudentNoShow = 'student_no_show',
  BothNoShow = 'both_no_show',
  Incomplete = 'incomplete',
  Completed = 'completed',
  Disputed = 'disputed',
  Compensated = 'compensated',
  Refunded = 'refunded',
  Expired = 'expired',
  Unknown = 'unknown',
}
