name: tilawa_ui_kit
resolution: workspace
description: UI library for Tilawa.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Utils
  google_fonts: ^8.1.0
  flex_color_scheme:
    path: ../flex_color_scheme
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.273

dev_dependencies:
  alchemist: ^0.14.0
  bloc_lint: ^0.4.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
