// Mocks generated by Mockito 5.4.6 from annotations
// in muzakri/test/features/downloads/presentation/bloc/downloads_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dartz_plus/dartz_plus.dart' as _i11;
import 'package:dio/src/adapter.dart' as _i5;
import 'package:dio/src/cancel_token.dart' as _i37;
import 'package:dio/src/dio.dart' as _i8;
import 'package:dio/src/dio_mixin.dart' as _i4;
import 'package:dio/src/options.dart' as _i3;
import 'package:dio/src/response.dart' as _i7;
import 'package:dio/src/transformer.dart' as _i6;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i33;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:muzakri/core/errors/failures.dart' as _i12;
import 'package:muzakri/core/services/analytics_service.dart' as _i30;
import 'package:muzakri/core/usecases/usecase.dart' as _i16;
import 'package:muzakri/features/downloads/data/services/download_notification_service.dart'
    as _i32;
import 'package:muzakri/features/downloads/data/services/download_service.dart'
    as _i31;
import 'package:muzakri/features/downloads/domain/entities/download_item.dart'
    as _i13;
import 'package:muzakri/features/downloads/domain/repositories/downloads_repository.dart'
    as _i2;
import 'package:muzakri/features/downloads/domain/usecases/cancel_download_use_case.dart'
    as _i29;
import 'package:muzakri/features/downloads/domain/usecases/check_download_access_use_case.dart'
    as _i24;
import 'package:muzakri/features/downloads/domain/usecases/check_surah_downloaded_use_case.dart'
    as _i21;
import 'package:muzakri/features/downloads/domain/usecases/clear_all_downloads_use_case.dart'
    as _i20;
import 'package:muzakri/features/downloads/domain/usecases/delete_download_use_case.dart'
    as _i18;
import 'package:muzakri/features/downloads/domain/usecases/delete_reciter_downloads_use_case.dart'
    as _i19;
import 'package:muzakri/features/downloads/domain/usecases/download_surah_use_case.dart'
    as _i17;
import 'package:muzakri/features/downloads/domain/usecases/get_download_item_use_case.dart'
    as _i28;
import 'package:muzakri/features/downloads/domain/usecases/get_download_status_use_case.dart'
    as _i35;
import 'package:muzakri/features/downloads/domain/usecases/get_downloads_by_reciter_use_case.dart'
    as _i9;
import 'package:muzakri/features/downloads/domain/usecases/get_total_downloads_size_use_case.dart'
    as _i15;
import 'package:muzakri/features/downloads/domain/usecases/get_valid_completed_downloads_use_case.dart'
    as _i23;
import 'package:muzakri/features/downloads/domain/usecases/observe_global_download_progress_use_case.dart'
    as _i34;
import 'package:muzakri/features/downloads/domain/usecases/play_all_downloads_use_case.dart'
    as _i26;
import 'package:muzakri/features/downloads/domain/usecases/play_download_use_case.dart'
    as _i25;
import 'package:muzakri/features/downloads/domain/usecases/remove_from_download_queue_use_case.dart'
    as _i36;
import 'package:muzakri/features/downloads/domain/usecases/retry_download_use_case.dart'
    as _i27;
import 'package:muzakri/features/downloads/domain/usecases/validate_downloaded_file_use_case.dart'
    as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDownloadsRepository_0 extends _i1.SmartFake
    implements _i2.DownloadsRepository {
  _FakeDownloadsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_1 extends _i1.SmartFake implements _i3.BaseOptions {
  _FakeBaseOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_2 extends _i1.SmartFake implements _i4.Interceptors {
  _FakeInterceptors_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_3 extends _i1.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_4 extends _i1.SmartFake implements _i6.Transformer {
  _FakeTransformer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5<T1> extends _i1.SmartFake implements _i7.Response<T1> {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_6 extends _i1.SmartFake implements _i8.Dio {
  _FakeDio_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDownloadsByReciterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDownloadsByReciterUseCase extends _i1.Mock
    implements _i9.GetDownloadsByReciterUseCase {
  MockGetDownloadsByReciterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<
    _i11.Either<_i12.Failure, Map<String, Map<String, List<_i13.DownloadItem>>>>
  >
  call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i10.Future<
                  _i11.Either<
                    _i12.Failure,
                    Map<String, Map<String, List<_i13.DownloadItem>>>
                  >
                >.value(
                  _i14.dummyValue<
                    _i11.Either<
                      _i12.Failure,
                      Map<String, Map<String, List<_i13.DownloadItem>>>
                    >
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i10.Future<
            _i11.Either<
              _i12.Failure,
              Map<String, Map<String, List<_i13.DownloadItem>>>
            >
          >);
}

/// A class which mocks [GetTotalDownloadsSizeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTotalDownloadsSizeUseCase extends _i1.Mock
    implements _i15.GetTotalDownloadsSizeUseCase {
  MockGetTotalDownloadsSizeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DownloadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeDownloadsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.DownloadsRepository);

  @override
  _i10.Future<_i11.Either<_i12.Failure, int>> call(_i16.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, int>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, int>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, int>>);
}

/// A class which mocks [DownloadSurahUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadSurahUseCase extends _i1.Mock
    implements _i17.DownloadSurahUseCase {
  MockDownloadSurahUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call({
    required String? surahId,
    required String? surahTitle,
    required String? reciterName,
    required int? reciterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #surahId: surahId,
              #surahTitle: surahTitle,
              #reciterName: reciterName,
              #reciterId: reciterId,
            }),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [], {
                  #surahId: surahId,
                  #surahTitle: surahTitle,
                  #reciterName: reciterName,
                  #reciterId: reciterId,
                }),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [DeleteDownloadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteDownloadUseCase extends _i1.Mock
    implements _i18.DeleteDownloadUseCase {
  MockDeleteDownloadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [downloadId]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [downloadId]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [DeleteReciterDownloadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteReciterDownloadsUseCase extends _i1.Mock
    implements _i19.DeleteReciterDownloadsUseCase {
  MockDeleteReciterDownloadsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#call, [reciterName]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [reciterName]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [ClearAllDownloadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearAllDownloadsUseCase extends _i1.Mock
    implements _i20.ClearAllDownloadsUseCase {
  MockClearAllDownloadsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [CheckSurahDownloadedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckSurahDownloadedUseCase extends _i1.Mock
    implements _i21.CheckSurahDownloadedUseCase {
  MockCheckSurahDownloadedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, bool>> call({
    required String? surahId,
    required String? reciterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #surahId: surahId,
              #reciterName: reciterName,
            }),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, bool>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, bool>>(
                this,
                Invocation.method(#call, [], {
                  #surahId: surahId,
                  #reciterName: reciterName,
                }),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, bool>>);
}

/// A class which mocks [ValidateDownloadedFileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateDownloadedFileUseCase extends _i1.Mock
    implements _i22.ValidateDownloadedFileUseCase {
  MockValidateDownloadedFileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, bool>> call(
    _i13.DownloadItem? downloadItem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [downloadItem]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, bool>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, bool>>(
                this,
                Invocation.method(#call, [downloadItem]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, bool>>);
}

/// A class which mocks [GetValidCompletedDownloadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetValidCompletedDownloadsUseCase extends _i1.Mock
    implements _i23.GetValidCompletedDownloadsUseCase {
  MockGetValidCompletedDownloadsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, List<_i13.DownloadItem>>> call(
    String? reciterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [reciterName]),
            returnValue:
                _i10.Future<
                  _i11.Either<_i12.Failure, List<_i13.DownloadItem>>
                >.value(
                  _i14.dummyValue<
                    _i11.Either<_i12.Failure, List<_i13.DownloadItem>>
                  >(this, Invocation.method(#call, [reciterName])),
                ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, List<_i13.DownloadItem>>>);
}

/// A class which mocks [CheckDownloadAccessUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckDownloadAccessUseCase extends _i1.Mock
    implements _i24.CheckDownloadAccessUseCase {
  MockCheckDownloadAccessUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, bool>> call(_i16.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, bool>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, bool>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, bool>>);
}

/// A class which mocks [PlayDownloadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayDownloadUseCase extends _i1.Mock
    implements _i25.PlayDownloadUseCase {
  MockPlayDownloadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(
    _i13.DownloadItem? downloadItem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [downloadItem]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [downloadItem]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [PlayAllDownloadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayAllDownloadsUseCase extends _i1.Mock
    implements _i26.PlayAllDownloadsUseCase {
  MockPlayAllDownloadsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(
    _i26.PlayAllDownloadsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [RetryDownloadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetryDownloadUseCase extends _i1.Mock
    implements _i27.RetryDownloadUseCase {
  MockRetryDownloadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [downloadId]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [downloadId]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [GetDownloadItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDownloadItemUseCase extends _i1.Mock
    implements _i28.GetDownloadItemUseCase {
  MockGetDownloadItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, _i13.DownloadItem?>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i10.Future<
                  _i11.Either<_i12.Failure, _i13.DownloadItem?>
                >.value(
                  _i14.dummyValue<
                    _i11.Either<_i12.Failure, _i13.DownloadItem?>
                  >(this, Invocation.method(#call, [id])),
                ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, _i13.DownloadItem?>>);
}

/// A class which mocks [CancelDownloadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelDownloadUseCase extends _i1.Mock
    implements _i29.CancelDownloadUseCase {
  MockCancelDownloadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i11.Either<_i12.Failure, void>> call(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [downloadId]),
            returnValue: _i10.Future<_i11.Either<_i12.Failure, void>>.value(
              _i14.dummyValue<_i11.Either<_i12.Failure, void>>(
                this,
                Invocation.method(#call, [downloadId]),
              ),
            ),
          )
          as _i10.Future<_i11.Either<_i12.Failure, void>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i30.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> logEvent(String? name, {Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [name], {#parameters: parameters}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logLogin({String? loginMethod}) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {#loginMethod: loginMethod}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logSignUp({String? signUpMethod}) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {#signUpMethod: signUpMethod}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logScreenView(String? screenName, {String? screenClass}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logScreenView,
              [screenName],
              {#screenClass: screenClass},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logAudioPlay(
    String? audioId, {
    String? audioName,
    String? artist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logAudioPlay,
              [audioId],
              {#audioName: audioName, #artist: artist},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logAudioPause(String? audioId) =>
      (super.noSuchMethod(
            Invocation.method(#logAudioPause, [audioId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logAudioStop(String? audioId) =>
      (super.noSuchMethod(
            Invocation.method(#logAudioStop, [audioId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logAudioSeek(String? audioId, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#logAudioSeek, [audioId, position]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logDownloadStart(
    String? downloadId, {
    String? fileName,
    int? fileSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logDownloadStart,
              [downloadId],
              {#fileName: fileName, #fileSize: fileSize},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logDownloadComplete(
    String? downloadId, {
    String? fileName,
    int? fileSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logDownloadComplete,
              [downloadId],
              {#fileName: fileName, #fileSize: fileSize},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logDownloadCancel(String? downloadId, {String? fileName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logDownloadCancel,
              [downloadId],
              {#fileName: fileName},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logPurchase(
    String? transactionId, {
    double? value,
    String? currency,
    String? itemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logPurchase,
              [transactionId],
              {#value: value, #currency: currency, #itemId: itemId},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logSubscriptionStart(
    String? subscriptionId, {
    String? planId,
    double? value,
    String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logSubscriptionStart,
              [subscriptionId],
              {#planId: planId, #value: value, #currency: currency},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logSubscriptionCancel(
    String? subscriptionId, {
    String? planId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logSubscriptionCancel,
              [subscriptionId],
              {#planId: planId},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logSearch(String? searchTerm, {int? resultCount}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logSearch,
              [searchTerm],
              {#resultCount: resultCount},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logShare(String? contentType, {String? itemId}) =>
      (super.noSuchMethod(
            Invocation.method(#logShare, [contentType], {#itemId: itemId}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logFavorite(String? itemId, {String? itemType}) =>
      (super.noSuchMethod(
            Invocation.method(#logFavorite, [itemId], {#itemType: itemType}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logRating(
    int? rating, {
    String? itemId,
    String? itemType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logRating,
              [rating],
              {#itemId: itemId, #itemType: itemType},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> resetAnalyticsData() =>
      (super.noSuchMethod(
            Invocation.method(#resetAnalyticsData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i31.DownloadService {
  MockDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i31.DownloadProgress> get globalProgressStream =>
      (super.noSuchMethod(
            Invocation.getter(#globalProgressStream),
            returnValue: _i10.Stream<_i31.DownloadProgress>.empty(),
          )
          as _i10.Stream<_i31.DownloadProgress>);

  @override
  _i10.Stream<_i31.DownloadProgress> getProgressStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressStream, [id]),
            returnValue: _i10.Stream<_i31.DownloadProgress>.empty(),
          )
          as _i10.Stream<_i31.DownloadProgress>);

  @override
  _i10.Future<List<String>> getActiveDownloadIds() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveDownloadIds, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<bool> isStatusDownloadActive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isStatusDownloadActive, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i13.DownloadStatus?> getStatus(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, [id]),
            returnValue: _i10.Future<_i13.DownloadStatus?>.value(),
          )
          as _i10.Future<_i13.DownloadStatus?>);

  @override
  _i10.Future<void> download({
    required String? id,
    required String? url,
    required String? filePath,
    required String? title,
    required String? reciterName,
    int? reciterId,
    bool? showNotification = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [], {
              #id: id,
              #url: url,
              #filePath: filePath,
              #title: title,
              #reciterName: reciterName,
              #reciterId: reciterId,
              #showNotification: showNotification,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> disposeService() =>
      (super.noSuchMethod(
            Invocation.method(#disposeService, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [DownloadNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadNotificationService extends _i1.Mock
    implements _i32.DownloadNotificationService {
  MockDownloadNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> showDownloadProgress({
    required String? downloadId,
    required String? title,
    required String? reciterName,
    required int? progress,
    required _i13.DownloadStatus? status,
    String? pendingMessage,
    String? progressMessage,
    String? completeMessage,
    String? failedMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDownloadProgress, [], {
              #downloadId: downloadId,
              #title: title,
              #reciterName: reciterName,
              #progress: progress,
              #status: status,
              #pendingMessage: pendingMessage,
              #progressMessage: progressMessage,
              #completeMessage: completeMessage,
              #failedMessage: failedMessage,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> showBatchDownloadProgress({
    required String? batchId,
    required String? title,
    required int? progress,
    required int? completedCount,
    required int? totalCount,
    required _i13.DownloadStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showBatchDownloadProgress, [], {
              #batchId: batchId,
              #title: title,
              #progress: progress,
              #completedCount: completedCount,
              #totalCount: totalCount,
              #status: status,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelNotification(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [downloadId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> handleNotificationResponse(
    _i33.NotificationResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleNotificationResponse, [response]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ObserveGlobalDownloadProgressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObserveGlobalDownloadProgressUseCase extends _i1.Mock
    implements _i34.ObserveGlobalDownloadProgressUseCase {
  MockObserveGlobalDownloadProgressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i31.DownloadProgress> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i10.Stream<_i31.DownloadProgress>.empty(),
          )
          as _i10.Stream<_i31.DownloadProgress>);
}

/// A class which mocks [GetDownloadStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDownloadStatusUseCase extends _i1.Mock
    implements _i35.GetDownloadStatusUseCase {
  MockGetDownloadStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i13.DownloadStatus?> call(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [taskId]),
            returnValue: _i10.Future<_i13.DownloadStatus?>.value(),
          )
          as _i10.Future<_i13.DownloadStatus?>);
}

/// A class which mocks [RemoveFromDownloadQueueUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFromDownloadQueueUseCase extends _i1.Mock
    implements _i36.RemoveFromDownloadQueueUseCase {
  MockRemoveFromDownloadQueueUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(String? taskId) => super.noSuchMethod(
    Invocation.method(#call, [taskId]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i8.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_1(this, Invocation.getter(#options)),
          )
          as _i3.BaseOptions);

  @override
  _i4.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_2(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i4.Interceptors);

  @override
  _i5.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_3(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i5.HttpClientAdapter);

  @override
  _i6.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_4(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i6.Transformer);

  @override
  set options(_i3.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i6.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i7.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i3.FileAccessMode? fileAccessMode = _i3.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i10.Future<_i7.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<dynamic>>);

  @override
  _i10.Future<_i7.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    _i37.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i3.FileAccessMode? fileAccessMode = _i3.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i10.Future<_i7.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<dynamic>>);

  @override
  _i10.Future<_i7.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i37.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i10.Future<_i7.Response<T>> fetch<T>(_i3.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i10.Future<_i7.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i10.Future<_i7.Response<T>>);

  @override
  _i8.Dio clone({
    _i3.BaseOptions? options,
    _i4.Interceptors? interceptors,
    _i5.HttpClientAdapter? httpClientAdapter,
    _i6.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_6(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i8.Dio);
}
