// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/prayer_times/domain/usecases/get_monthly_prayer_times_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tilawa/features/prayer_times/domain/entities/prayer_settings_entity.dart'
    as _i4;
import 'package:tilawa/features/prayer_times/domain/entities/prayer_time_entity.dart'
    as _i2;
import 'package:tilawa/features/prayer_times/domain/repositories/prayer_times_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrayerTimeEntity_0 extends _i1.SmartFake
    implements _i2.PrayerTimeEntity {
  _FakePrayerTimeEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationResult_1 extends _i1.SmartFake
    implements _i3.LocationResult {
  _FakeLocationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrayerSettingsEntity_2 extends _i1.SmartFake
    implements _i4.PrayerSettingsEntity {
  _FakePrayerSettingsEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrayerTimesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerTimesRepository extends _i1.Mock
    implements _i3.PrayerTimesRepository {
  MockPrayerTimesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PrayerTimeEntity> getPrayerTimes({
    required double? latitude,
    required double? longitude,
    required DateTime? date,
    required _i4.PrayerSettingsEntity? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPrayerTimes, [], {
              #latitude: latitude,
              #longitude: longitude,
              #date: date,
              #settings: settings,
            }),
            returnValue: _i5.Future<_i2.PrayerTimeEntity>.value(
              _FakePrayerTimeEntity_0(
                this,
                Invocation.method(#getPrayerTimes, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                  #date: date,
                  #settings: settings,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PrayerTimeEntity>);

  @override
  _i5.Future<List<_i2.PrayerTimeEntity>> getPrayerTimesForRange({
    required double? latitude,
    required double? longitude,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i4.PrayerSettingsEntity? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPrayerTimesForRange, [], {
              #latitude: latitude,
              #longitude: longitude,
              #startDate: startDate,
              #endDate: endDate,
              #settings: settings,
            }),
            returnValue: _i5.Future<List<_i2.PrayerTimeEntity>>.value(
              <_i2.PrayerTimeEntity>[],
            ),
          )
          as _i5.Future<List<_i2.PrayerTimeEntity>>);

  @override
  _i5.Future<List<_i2.PrayerTimeEntity>> getMonthlyPrayerTimes({
    required double? latitude,
    required double? longitude,
    required int? year,
    required int? month,
    required _i4.PrayerSettingsEntity? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyPrayerTimes, [], {
              #latitude: latitude,
              #longitude: longitude,
              #year: year,
              #month: month,
              #settings: settings,
            }),
            returnValue: _i5.Future<List<_i2.PrayerTimeEntity>>.value(
              <_i2.PrayerTimeEntity>[],
            ),
          )
          as _i5.Future<List<_i2.PrayerTimeEntity>>);

  @override
  _i5.Future<_i3.LocationResult> getCurrentLocation({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<_i3.LocationResult>.value(
              _FakeLocationResult_1(
                this,
                Invocation.method(#getCurrentLocation, [], {
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.LocationResult>);

  @override
  _i5.Future<String?> getLocationName({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationName, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveSettings(_i4.PrayerSettingsEntity? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.PrayerSettingsEntity> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i5.Future<_i4.PrayerSettingsEntity>.value(
              _FakePrayerSettingsEntity_2(
                this,
                Invocation.method(#loadSettings, []),
              ),
            ),
          )
          as _i5.Future<_i4.PrayerSettingsEntity>);

  @override
  _i5.Future<bool> hasLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasLocationPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
