// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJQ04bgIRkijYOhJdgl4wdhPTB99XFUk',
    appId: '1:181575856185:android:70e2d3035b9d23a3381de8',
    messagingSenderId: '181575856185',
    projectId: 'quran-playera-app',
    storageBucket: 'quran-playera-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIxMc7sRMmNYmYCo-IJbgHo8H9avi4ws',
    appId: '1:181575856185:ios:86db9760986755b1381de8',
    messagingSenderId: '181575856185',
    projectId: 'quran-playera-app',
    storageBucket: 'quran-playera-app.firebasestorage.app',
    androidClientId:
        '181575856185-o5o9q4t3sc0tsoik2c9ibkkc7b8d8kqp.apps.googleusercontent.com',
    iosClientId:
        '181575856185-eamub0dns4ickt7ke4l3afu60vgtlj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.muzakri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIxMc7sRMmNYmYCo-IJbgHo8H9avi4ws',
    appId: '1:181575856185:ios:8b8b3760623dfbb2381de8',
    messagingSenderId: '181575856185',
    projectId: 'quran-playera-app',
    storageBucket: 'quran-playera-app.firebasestorage.app',
    androidClientId:
        '181575856185-o5o9q4t3sc0tsoik2c9ibkkc7b8d8kqp.apps.googleusercontent.com',
    iosClientId:
        '181575856185-juas6d0562lrjcdtlq66n31141cejifs.apps.googleusercontent.com',
    iosBundleId: 'com.quran.player.app',
  );
}
