name: tilawa
resolution: workspace
description: An Audio Quran Player project.

publish_to: none
version: 1.0.5+34

environment:
  sdk: ^3.12.0

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  cloud_firestore: ^6.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  coverage: ^1.15.0
  credential_manager: ^2.0.8
  cupertino_icons: ^1.0.8
  dartz_plus: ^0.3.0
  dio: ^5.9.0
  equatable: ^2.0.8
  fake_async: ^1.3.3
  firebase_analytics: ^12.1.0
  firebase_app_check: ^0.4.4+1
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_crashlytics: ^5.2.2
  firebase_messaging: ^16.2.2
  firebase_performance: ^0.11.4+1
  flex_color_scheme:
    path: ../../packages/flex_color_scheme
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_downloader: ^1.12.0
  flutter_local_notifications: ^21.0.0-dev.1
  flutter_local_notifications_platform_interface: ^11.0.0-dev.1
  flutter_timezone: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  geolocator: ^14.0.2
  get_it: ^9.2.0
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  hive_ce: ^2.19.1
  http: ^1.6.0
  hugeicons: ^1.1.4
  hydrated_bloc: ^11.0.0
  in_app_purchase: ^3.2.3
  in_app_update: ^4.2.5
  cloud_functions: ^6.3.1
  injectable: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.10.0
  just_audio: ^0.10.5
  logger: ^2.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  qibla:
    path: ../../packages/qibla
  tilawa_core:
    path: ../../packages/core
  tilawa_ui_kit:
    path: ../../packages/ui_kit
  quran_qcf:
    path: ../../packages/quran_qcf
  quran_image:
    path: ../../packages/quran_image

  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  stream_transform: ^2.1.1
  term_glyph: ^1.2.2
  timezone: ^0.11.0
  tutorial_coach_mark: ^1.3.3
  geocoding: ^4.0.0
  package_info_plus: ^9.0.0
  device_preview: ^1.3.1
  image_picker: ^1.2.1
  vibration: ^3.1.8
  meta: ^1.17.0
  in_app_review: ^2.0.12
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  fake_cloud_firestore: ^4.0.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  go_router_builder: ^4.3.0
  injectable_generator: ^3.0.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.11.3
  mockito: ^5.6.1
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  vibration_platform_interface: ^0.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - shorebird.yaml
    - assets/images/
    - assets/json/
    - assets/data/
    - assets/icons/
    - assets/audio/
