import 'package:get_it/get_it.dart';
import 'package:tilawa/core/di/adhan_module.dart';
import 'package:tilawa/core/di/external_dependencies_module.dart';
import 'package:tilawa/features/app_review/di/app_review_module.dart';
import 'package:tilawa/features/app_review/di/app_review_policy_module.dart';
import 'package:tilawa/features/downloads/di/downloads_module.dart';
import 'package:tilawa/features/home/di/home_screen_module.dart';
import 'package:tilawa/features/recitation_practice/di/recitation_practice_module.dart';
import 'package:tilawa/features/settings/di/settings_module.dart';
import 'package:tilawa_core/di/tilawa_core_di.dart';
import 'package:tilawa/features/auth/di/auth_di.dart';
import 'package:tilawa/features/prayer_times/di/prayer_times_di.dart';
import 'package:tilawa/features/recitation_practice/di/recitation_practice_di.dart';
import 'package:tilawa/features/reciters/di/reciters_di.dart';
import 'package:tilawa/features/share/di/share_di.dart';
import 'package:tilawa/features/theme/di/theme_di.dart';
import 'package:tilawa/core/di/core_services_di.dart';
import 'package:tilawa/features/app_review/di/app_review_di.dart';
import 'package:tilawa/features/athkar/di/athkar_di.dart';
import 'package:tilawa/features/smart_khatma/smart_khatma_dependencies.dart';
import 'package:tilawa/features/audio_player/di/audio_player_di.dart';
import 'package:tilawa/features/daily_guidance/di/daily_guidance_di.dart';
import 'package:tilawa/features/downloads/di/downloads_di.dart';
import 'package:tilawa/features/forced_update/di/forced_update_di.dart';
import 'package:tilawa/features/notifications/di/notifications_di.dart';
import 'package:tilawa/features/quran_sessions/di/quran_sessions_di.dart';
import 'package:tilawa/features/sadaqah_jariyah/di/sadaqah_jariyah_di.dart';
import 'package:tilawa/features/settings/di/settings_di.dart';
import 'package:tilawa/features/whats_new/di/whats_new_di.dart';
import 'package:tilawa/features/reels/di/reels_di.dart';
import 'package:tilawa/features/quran_reader/di/quran_reader_di.dart';
import 'package:tilawa/features/onboarding/di/onboarding_di.dart';
import 'package:tilawa/features/qibla/di/qibla_di.dart';
import 'package:tilawa/features/localization/di/localization_di.dart';
import 'package:tilawa/core/di/misc_di.dart';
import 'package:tilawa/features/playlists/di/playlists_di.dart';
import 'package:tilawa/features/splash/di/splash_di.dart';
import 'package:tilawa/features/surah/di/surah_di.dart';
import 'package:tilawa/features/support/di/support_di.dart';
import 'package:tilawa/features/radio/di/radio_di.dart';
import 'package:tilawa/features/home/di/home_di.dart';
import 'package:tilawa/features/premium/di/premium_di.dart';
import 'package:tilawa/features/bookmarks/di/bookmarks_di.dart';
import 'package:tilawa/features/history/di/history_di.dart';
import 'package:tilawa/shared/di/shared_di.dart';

/// Registers the former injectable graph via explicit feature modules.
void registerManualDependencyGraph(GetIt getIt) {
  TilawaCoreDi.register(getIt);
  ExternalDependenciesModule.register(getIt);
  AppReviewModule.register(getIt);
  AppReviewPolicyModule.register(getIt);
  DownloadsModule.register(getIt);
  HomeScreenModule.register(getIt);
  RecitationPracticeModule.register(getIt);
  AdhanModule.register(getIt);
  SettingsModule.register(getIt);
  AuthDi.register(getIt);
  PrayerTimesDi.register(getIt);
  RecitationPracticeDi.register(getIt);
  RecitersDi.register(getIt);
  ShareDi.register(getIt);
  ThemeDi.register(getIt);
  CoreDi.register(getIt);
  AppReviewDi.register(getIt);
  AthkarDi.register(getIt);
  SmartKhatmaDependencies.register(getIt);
  AudioPlayerDi.register(getIt);
  DailyGuidanceDi.register(getIt);
  DownloadsDi.register(getIt);
  ForcedUpdateDi.register(getIt);
  NotificationsDi.register(getIt);
  QuranSessionsDi.register(getIt);
  SadaqahJariyahDi.register(getIt);
  SettingsDi.register(getIt);
  WhatsNewDi.register(getIt);
  ReelsDi.register(getIt);
  QuranReaderDi.register(getIt);
  OnboardingDi.register(getIt);
  QiblaDi.register(getIt);
  LocalizationDi.register(getIt);
  MiscDi.register(getIt);
  PlaylistsDi.register(getIt);
  SplashDi.register(getIt);
  SurahDi.register(getIt);
  SupportDi.register(getIt);
  RadioDi.register(getIt);
  HomeDi.register(getIt);
  PremiumDi.register(getIt);
  BookmarksDi.register(getIt);
  HistoryDi.register(getIt);
  SharedDi.register(getIt);
}
