/// Declarative side-effect intent emitted by transition validation.
enum TransitionSideEffect {
  softHoldSlotTtl,
  capturePayment,
  hardLockSlot,
  createSessionDocument,
  notifyBothParties,
  scheduleReminder,
  openCallRoom,
  promptReview,
  notifyCounterparty,
  swapSlotAtomically,
  releaseOldSlot,
  lockNewSlot,
  applyCancellationPolicy,
  autoCompensateStudent,
  adminChooseCompensation,
  markAttendanceFromJoinLogs,
  openManualReviewCase,
  executeCompensationPolicy,
  executePaymentRefund,
  releaseSlot,
  voidPayment,
  appendAuditTrail,
}
