// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/playlists/data/repositories/playlists_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tilawa/features/playlists/data/datasources/playlists_local_datasource.dart'
    as _i2;
import 'package:tilawa/features/playlists/domain/entities/playlist.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlaylistsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistsLocalDataSource extends _i1.Mock
    implements _i2.PlaylistsLocalDataSource {
  MockPlaylistsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Playlist>> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue: _i3.Future<List<_i4.Playlist>>.value(<_i4.Playlist>[]),
          )
          as _i3.Future<List<_i4.Playlist>>);

  @override
  _i3.Future<_i4.Playlist?> getPlaylistById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistById, [id]),
            returnValue: _i3.Future<_i4.Playlist?>.value(),
          )
          as _i3.Future<_i4.Playlist?>);

  @override
  _i3.Future<void> savePlaylist(_i4.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#savePlaylist, [playlist]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveAllPlaylists(List<_i4.Playlist>? playlists) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllPlaylists, [playlists]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllPlaylists, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> doesPlaylistNameExist(String? name, {String? excludeId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #doesPlaylistNameExist,
              [name],
              {#excludeId: excludeId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getPlaylistsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistsCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalItemsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalItemsCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> generatePlaylistId() =>
      (super.noSuchMethod(
            Invocation.method(#generatePlaylistId, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generatePlaylistId, []),
              ),
            ),
          )
          as _i3.Future<String>);
}
