name: quran_qcf
resolution: workspace
description: "Quran Reader"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.1

dependencies:
  archive: ^4.0.9
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  get_it: ^9.2.1
  logger: ^2.7.0
  path_provider: ^2.1.5
  tilawa_ui_kit:
    path: ../ui_kit

dev_dependencies:
  bloc_lint: ^0.4.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quran_fonts/qpc-v4.json
    - assets/quran_fonts/quran_page_index.json

  fonts:
    - family: QCF_BSML
      fonts:
        - asset: assets/quran_fonts/QCF4_QBSML-Regular.ttf
