name: tilawa_ui
resolution: workspace
description: UI library for Tilawa.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # Core
  tilawa_core:
    path: ../core

  # Utils
  google_fonts: ^8.0.0
  flex_color_scheme: ^8.4.0
  skeletonizer: ^2.1.2
  gap: ^3.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
