import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:quran_image/domain/entities/verse_marker_data.dart';
import 'package:quran_image/quran_image_page.dart';
import 'package:quran_image/verse_marker.dart';
import 'package:quran_image/verse_marker_layout.dart';

import 'quran_image_test_bootstrap.dart';

/// Portrait-first logical sizes (width × height in dp): phones and tablets.
///
/// Landscape cases are generated by swapping width and height so each device
/// class is exercised in both orientations.
final _portraitLogicalSizes = <Size>[
  const Size(280, 640),
  const Size(320, 568),
  const Size(360, 780),
  const Size(375, 812),
  const Size(390, 844),
  const Size(393, 852),
  const Size(412, 915),
  const Size(414, 896),
  const Size(428, 926),
  const Size(480, 854),
  const Size(600, 960),
  const Size(768, 1024),
  const Size(834, 1194),
];

/// Square viewports: neither portrait nor landscape branch in layout math.
final _squareLogicalSizes = <Size>[
  const Size(390, 390),
  const Size(600, 600),
  const Size(840, 840),
];

/// All [QuranImagePage] layout scenarios: portrait, landscape, square.
List<({String label, Size size})> _quranImagePageLayoutCases() {
  final cases = <({String label, Size size})>[];

  for (final s in _portraitLogicalSizes) {
    cases.add((
      label: 'portrait ${s.width.toInt()}×${s.height.toInt()}',
      size: s,
    ));
    final land = Size(s.height, s.width);
    if (land != s) {
      cases.add((
        label: 'landscape ${land.width.toInt()}×${land.height.toInt()}',
        size: land,
      ));
    }
  }

  for (final s in _squareLogicalSizes) {
    cases.add((
      label: 'square ${s.width.toInt()}×${s.height.toInt()}',
      size: s,
    ));
  }

  return cases;
}

Future<void> _pumpQuranImagePage(
  WidgetTester tester, {
  required Size logicalSize,
}) async {
  tester.view.physicalSize = logicalSize;
  tester.view.devicePixelRatio = 1.0;
  addTearDown(tester.view.resetPhysicalSize);
  addTearDown(tester.view.resetDevicePixelRatio);

  await tester.pumpWidget(
    MediaQuery(
      data: MediaQueryData(size: logicalSize),
      child: const MaterialApp(
        home: Scaffold(
          body: QuranImagePage(pageNumber: 1),
        ),
      ),
    ),
  );
  await tester.pump();
}

void main() {
  late Directory tempDirectory;

  setUp(() async {
    tempDirectory = await bootstrapQuranImagePageTest();
  });

  tearDown(() async {
    await tearDownQuranImageTest(tempDirectory);
  });

  group('QuranImagePage — portrait, landscape, square', () {
    for (final (:label, :size) in _quranImagePageLayoutCases()) {
      testWidgets('builds without error ($label)', (tester) async {
        await _pumpQuranImagePage(tester, logicalSize: size);

        expect(tester.takeException(), isNull);
        expect(find.byType(Image), findsWidgets);
      });
    }
  });

  group('VerseMarkersOverlay — layout width vs stale pageWidth', () {
    testWidgets(
      'portrait-like box: painted width must not follow stale pageWidth',
      (tester) async {
        const boxWidth = 320.0;
        const boxHeight = 520.0;
        const wrongPageWidth = 480.0;
        const centerX = 0.4;
        final markers = <VerseMarkerData>[
          VerseMarkerData(sura: 48, ayah: 1, line: 2, centerX: centerX),
        ];
        final lineHeight = 24.0;
        final yOffsets = List<double>.generate(15, (i) => i * lineHeight);

        await tester.pumpWidget(
          MaterialApp(
            home: Scaffold(
              body: Center(
                child: SizedBox(
                  width: boxWidth,
                  height: boxHeight,
                  child: VerseMarkersOverlay(
                    markers: markers,
                    pageWidth: wrongPageWidth,
                    lineHeight: lineHeight,
                    yOffsets: yOffsets,
                  ),
                ),
              ),
            ),
          ),
        );
        await tester.pump();

        expect(tester.takeException(), isNull);

        final correctLeft = VerseMarkerLayout.markerLeftOffset(
          centerX: centerX,
          layoutWidth: boxWidth,
        );
        final staleLeft = VerseMarkerLayout.markerLeftOffset(
          centerX: centerX,
          layoutWidth: wrongPageWidth,
        );
        expect(correctLeft, isNot(closeTo(staleLeft, 1.0)));
      },
    );

    testWidgets(
      'landscape-like wide box: painted width must not follow stale pageWidth',
      (tester) async {
        const boxWidth = 812.0;
        const boxHeight = 280.0;
        const wrongPageWidth = 360.0;
        const centerX = 0.55;
        final markers = <VerseMarkerData>[
          VerseMarkerData(sura: 2, ayah: 255, line: 7, centerX: centerX),
        ];
        final lineHeight = 20.0;
        final yOffsets = List<double>.generate(15, (i) => i * lineHeight);

        await tester.pumpWidget(
          MaterialApp(
            home: Scaffold(
              body: Center(
                child: SizedBox(
                  width: boxWidth,
                  height: boxHeight,
                  child: VerseMarkersOverlay(
                    markers: markers,
                    pageWidth: wrongPageWidth,
                    lineHeight: lineHeight,
                    yOffsets: yOffsets,
                  ),
                ),
              ),
            ),
          ),
        );
        await tester.pump();

        expect(tester.takeException(), isNull);

        final correctLeft = VerseMarkerLayout.markerLeftOffset(
          centerX: centerX,
          layoutWidth: boxWidth,
        );
        final staleLeft = VerseMarkerLayout.markerLeftOffset(
          centerX: centerX,
          layoutWidth: wrongPageWidth,
        );
        expect(correctLeft, isNot(closeTo(staleLeft, 1.0)));
      },
    );

    testWidgets('tablet landscape width: regression on wide canvas', (
      tester,
    ) async {
      const boxWidth = 1194.0;
      const boxHeight = 834.0;
      const wrongPageWidth = 390.0;
      const centerX = 0.12;
      final markers = <VerseMarkerData>[
        VerseMarkerData(sura: 1, ayah: 7, line: 14, centerX: centerX),
      ];
      final lineHeight = 28.0;
      final yOffsets = List<double>.generate(15, (i) => i * lineHeight);

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Center(
              child: SizedBox(
                width: boxWidth,
                height: boxHeight,
                child: VerseMarkersOverlay(
                  markers: markers,
                  pageWidth: wrongPageWidth,
                  lineHeight: lineHeight,
                  yOffsets: yOffsets,
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pump();

      expect(tester.takeException(), isNull);

      final correctLeft = VerseMarkerLayout.markerLeftOffset(
        centerX: centerX,
        layoutWidth: boxWidth,
      );
      final staleLeft = VerseMarkerLayout.markerLeftOffset(
        centerX: centerX,
        layoutWidth: wrongPageWidth,
      );
      expect(correctLeft, isNot(closeTo(staleLeft, 1.0)));
    });
  });
}
