// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/prayer_times/data/repositories/prayer_times_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tilawa/features/prayer_times/data/datasources/location_datasource.dart'
    as _i6;
import 'package:tilawa/features/prayer_times/data/datasources/prayer_settings_datasource.dart'
    as _i4;
import 'package:tilawa/features/prayer_times/domain/entities/entities.dart'
    as _i2;
import 'package:tilawa/features/prayer_times/domain/repositories/prayer_times_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrayerSettingsEntity_0 extends _i1.SmartFake
    implements _i2.PrayerSettingsEntity {
  _FakePrayerSettingsEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationResult_1 extends _i1.SmartFake
    implements _i3.LocationResult {
  _FakeLocationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrayerSettingsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerSettingsDataSource extends _i1.Mock
    implements _i4.PrayerSettingsDataSource {
  MockPrayerSettingsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PrayerSettingsEntity> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i5.Future<_i2.PrayerSettingsEntity>.value(
              _FakePrayerSettingsEntity_0(
                this,
                Invocation.method(#loadSettings, []),
              ),
            ),
          )
          as _i5.Future<_i2.PrayerSettingsEntity>);

  @override
  _i5.Future<void> saveSettings(_i2.PrayerSettingsEntity? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearSettings, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LocationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationDataSource extends _i1.Mock
    implements _i6.LocationDataSource {
  MockLocationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.LocationResult> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i5.Future<_i3.LocationResult>.value(
              _FakeLocationResult_1(
                this,
                Invocation.method(#getCurrentLocation, []),
              ),
            ),
          )
          as _i5.Future<_i3.LocationResult>);

  @override
  _i5.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
