name: qibla
resolution: workspace
description: A Qibla direction finder package.
  that allows you to display Qibla direction in you app with support for both Android and iOS
version: 3.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_compass_v2: ^1.0.3
  geolocator: ^14.0.2
  plugin_platform_interface: ^2.1.8
  stream_transform: ^2.1.1
  vector_math: ^2.1.4

flutter:
  plugin:
    platforms:
      android:
        package: ml.medyas.qibla
        pluginClass: QiblaPlugin
      ios:
        pluginClass: QiblaPlugin

dev_dependencies:
  bloc_lint: ^0.3.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  mocktail: ^1.0.4
