import json
import os
import glob
from collections import defaultdict

def find_issues():
    # Paths
    base_dir = "/Users/mohammadkamel/flutter_projects/tilawa_workspace/apps/quran_image"
    debug_dir = os.path.join(base_dir, "assets/data/quran_marker_debug_coordinates")
    prod_file = os.path.join(base_dir, "assets/data/verse_marker_coordinates.json")
    
    # Heuristic thresholds
    PLACEHOLDER_X = 0.0535
    CENTERED_END_X = 0.185
    SHORT_LINE_THRESHOLD = 3
    
    issues = []
    
    # 1. Load Production Data for Sync Check
    try:
        with open(prod_file, "r") as f:
            prod_data = json.load(f)
        # Build a lookup for production: (page, sura, ayah) -> centerX
        prod_lookup = {}
        for page_num_str, markers in prod_data.items():
            page = int(page_num_str)
            for item in markers:
                sura = item.get("sura")
                ayah = item.get("ayah")
                prod_lookup[(page, sura, ayah)] = item.get("centerX")
    except Exception as e:
        print(f"Error reading production file: {e}")
        prod_lookup = {}

    # 2. Iterate through Debug Files
    files = glob.glob(os.path.join(debug_dir, "*.json"))
    
    for file_path in sorted(files, key=lambda x: int(os.path.basename(x).split(".")[0])):
        page_num_str = os.path.basename(file_path).split(".")[0]
        page_num = int(page_num_str)
        
        try:
            with open(file_path, "r") as f:
                data = json.load(f)
        except Exception as e:
            print(f"Error reading {file_path}: {e}")
            continue

        # Group markers by line
        lines = defaultdict(list)
        for marker in data:
            lines[marker.get("line")].append(marker)
            
        for line_idx, markers in lines.items():
            # Rule 1 & 2: Placeholder check on short/centered lines
            if len(markers) < SHORT_LINE_THRESHOLD:
                for m in markers:
                    curr_x = m.get("centerX")
                    
                    # If it's a short line and using the "full line end" placeholder
                    if abs(curr_x - PLACEHOLDER_X) < 0.0001:
                        issues.append({
                            "page": page_num,
                            "line": line_idx,
                            "sura": m.get("sura"),
                            "ayah": m.get("ayah"),
                            "issue": "Placeholder 0.0535 on short line (likely centered)",
                            "current_x": curr_x,
                            "severity": "HIGH"
                        })
                    
                    # Single ayah line check
                    if len(markers) == 1:
                        if curr_x > 0.45 or curr_x < 0.25:
                            issues.append({
                                "page": page_num,
                                "line": line_idx,
                                "sura": m.get("sura"),
                                "ayah": m.get("ayah"),
                                "issue": "Single ayah on line with suspicious X (check centering)",
                                "current_x": curr_x,
                                "severity": "MEDIUM"
                            })

            # Rule 3: Sync Check
            for m in markers:
                sura = m.get("sura")
                ayah = m.get("ayah")
                curr_x = m.get("centerX")
                
                prod_x = prod_lookup.get((page_num, sura, ayah))
                if prod_x is not None and abs(curr_x - prod_x) > 0.0001:
                    issues.append({
                        "page": page_num,
                        "line": line_idx,
                        "sura": sura,
                        "ayah": ayah,
                        "issue": f"Desync: Debug({curr_x}) != Prod({prod_x})",
                        "current_x": curr_x,
                        "severity": "SYNC"
                    })
    
    return issues

def generate_report(issues):
    report_path = "/Users/mohammadkamel/.gemini/antigravity/brain/adddc813-a35e-452a-a941-868f1d742a4e/coordinate_diagnostic_report.md"
    
    with open(report_path, "w") as f:
        f.write("# Coordinate Diagnostic Report\n\n")
        f.write("Generated by `find_coordinate_issues.py`.\n\n")
        
        # Summary
        summary = defaultdict(int)
        for i in issues:
            summary[i['issue']] += 1
            
        f.write("## Summary\n")
        for issue_type, count in summary.items():
            f.write(f"- **{issue_type}**: {count}\n")
        f.write("\n")
        
        # Table
        f.write("## Issues List\n\n")
        f.write("| Page | Line | Surah | Ayah | Severity | Issue | Current X |\n")
        f.write("|------|------|-------|------|----------|-------|-----------|\n")
        
        # Sort by severity and then page
        severity_map = {"HIGH": 0, "MEDIUM": 1, "SYNC": 2}
        sorted_issues = sorted(issues, key=lambda i: (severity_map.get(i['severity'], 9), i['page']))
        
        for i in sorted_issues:
            f.write(f"| {i['page']} | {i['line']} | {i['sura']} | {i['ayah']} | {i['severity']} | {i['issue']} | {i['current_x']} |\n")

if __name__ == "__main__":
    print("Running diagnostic script...")
    issues = find_issues()
    generate_report(issues)
    print(f"Done! Found {len(issues)} issues. Report generated.")
