// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/athkar/data/repositories/athkar_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tilawa/features/athkar/data/datasources/athkar_local_datasource.dart'
    as _i2;
import 'package:tilawa/features/athkar/data/models/athkar_category_model.dart'
    as _i4;
import 'package:tilawa/features/athkar/data/models/athkar_item_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AthkarLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAthkarLocalDataSource extends _i1.Mock
    implements _i2.AthkarLocalDataSource {
  MockAthkarLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AthkarCategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<_i4.AthkarCategoryModel>>.value(
              <_i4.AthkarCategoryModel>[],
            ),
          )
          as _i3.Future<List<_i4.AthkarCategoryModel>>);

  @override
  _i3.Future<List<_i5.AthkarItemModel>> getAthkarByCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getAthkarByCategory, [categoryId]),
            returnValue: _i3.Future<List<_i5.AthkarItemModel>>.value(
              <_i5.AthkarItemModel>[],
            ),
          )
          as _i3.Future<List<_i5.AthkarItemModel>>);
}
