// Mocks generated by Mockito 5.4.6 from annotations
// in muzakri/test/integration/downloads_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:muzakri/features/downloads/data/datasources/downloads_local_datasource.dart'
    as _i2;
import 'package:muzakri/features/downloads/data/services/download_notification_service.dart'
    as _i6;
import 'package:muzakri/features/downloads/domain/entities/download_item.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DownloadsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsLocalDataSource extends _i1.Mock
    implements _i2.DownloadsLocalDataSource {
  MockDownloadsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DownloadItem>> getDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloads, []),
            returnValue: _i3.Future<List<_i4.DownloadItem>>.value(
              <_i4.DownloadItem>[],
            ),
          )
          as _i3.Future<List<_i4.DownloadItem>>);

  @override
  _i3.Future<void> saveDownloads(List<_i4.DownloadItem>? downloads) =>
      (super.noSuchMethod(
            Invocation.method(#saveDownloads, [downloads]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addDownload(_i4.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#addDownload, [download]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDownload(_i4.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#updateDownload, [download]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownload, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllDownloads, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getDownloadsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsDirectory, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getDownloadsDirectory, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  bool isFileExists(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#isFileExists, [filePath]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> deleteFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [filePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DownloadNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadNotificationService extends _i1.Mock
    implements _i6.DownloadNotificationService {
  MockDownloadNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showDownloadProgress({
    required String? downloadId,
    required String? title,
    required String? reciterName,
    required int? progress,
    required _i4.DownloadStatus? status,
    String? pendingMessage,
    String? progressMessage,
    String? completeMessage,
    String? failedMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDownloadProgress, [], {
              #downloadId: downloadId,
              #title: title,
              #reciterName: reciterName,
              #progress: progress,
              #status: status,
              #pendingMessage: pendingMessage,
              #progressMessage: progressMessage,
              #completeMessage: completeMessage,
              #failedMessage: failedMessage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotification(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [downloadId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> handleNotificationResponse(
    _i7.NotificationResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleNotificationResponse, [response]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
