// Mocks generated by Mockito 5.4.6 from annotations
// in tilawa/test/features/downloads/presentation/widgets/download_item_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i4;

import 'package:audio_service/audio_service.dart' as _i5;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i15;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tilawa/features/audio_player/presentation/bloc/audio_player_bloc.dart'
    as _i3;
import 'package:tilawa/features/downloads/data/models/download_progress.dart'
    as _i12;
import 'package:tilawa/features/downloads/data/services/download_notification_service.dart'
    as _i14;
import 'package:tilawa/features/downloads/data/services/download_queue_manager.dart'
    as _i10;
import 'package:tilawa/features/downloads/data/services/download_service.dart'
    as _i11;
import 'package:tilawa/features/downloads/domain/entities/download_item.dart'
    as _i13;
import 'package:tilawa/features/downloads/domain/repositories/downloads_repository.dart'
    as _i16;
import 'package:tilawa/features/downloads/presentation/bloc/downloads_bloc.dart'
    as _i2;
import 'package:tilawa/features/downloads/presentation/bloc/downloads_status.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDownloadsState_0 extends _i1.SmartFake
    implements _i2.DownloadsState {
  _FakeDownloadsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioPlayerState_1 extends _i1.SmartFake
    implements _i3.AudioPlayerState {
  _FakeAudioPlayerState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaItem_3 extends _i1.SmartFake implements _i5.MediaItem {
  _FakeMediaItem_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsBloc extends _i1.Mock implements _i2.DownloadsBloc {
  MockDownloadsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i7.DownloadsStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i6.Stream<_i7.DownloadsStatus>.empty(),
          )
          as _i6.Stream<_i7.DownloadsStatus>);

  @override
  _i2.DownloadsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDownloadsState_0(this, Invocation.getter(#state)),
          )
          as _i2.DownloadsState);

  @override
  _i6.Stream<_i2.DownloadsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.DownloadsState>.empty(),
          )
          as _i6.Stream<_i2.DownloadsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i2.DownloadsState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i2.DownloadsState?);

  @override
  Map<String, dynamic>? toJson(_i2.DownloadsState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i2.DownloadsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.DownloadsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.DownloadsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.DownloadsEvent>(
    _i9.EventHandler<E, _i2.DownloadsState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i2.DownloadsEvent, _i2.DownloadsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i2.DownloadsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i2.DownloadsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i9.Storage? storage,
    _i9.OnHydrationError? onError = _i9.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AudioPlayerBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerBloc extends _i1.Mock implements _i3.AudioPlayerBloc {
  MockAudioPlayerBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioPlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAudioPlayerState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AudioPlayerState);

  @override
  _i6.Stream<_i3.AudioPlayerState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.AudioPlayerState>.empty(),
          )
          as _i6.Stream<_i3.AudioPlayerState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.AudioPlayerState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i3.AudioPlayerState?);

  @override
  Map<String, dynamic>? toJson(_i3.AudioPlayerState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i3.AudioPlayerEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AudioPlayerEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AudioPlayerState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AudioPlayerEvent>(
    _i9.EventHandler<E, _i3.AudioPlayerState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i3.AudioPlayerEvent, _i3.AudioPlayerState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.AudioPlayerEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i3.AudioPlayerState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i9.Storage? storage,
    _i9.OnHydrationError? onError = _i9.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DownloadQueueManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadQueueManager extends _i1.Mock
    implements _i10.DownloadQueueManager {
  MockDownloadQueueManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get maxConcurrentDownloads =>
      (super.noSuchMethod(
            Invocation.getter(#maxConcurrentDownloads),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_2(this, Invocation.getter(#locale)),
          )
          as _i4.Locale);

  @override
  int get queueLength =>
      (super.noSuchMethod(Invocation.getter(#queueLength), returnValue: 0)
          as int);

  @override
  int get activeDownloadsCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeDownloadsCount),
            returnValue: 0,
          )
          as int);

  @override
  _i6.Stream<_i10.QueueUpdate> get queueUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#queueUpdates),
            returnValue: _i6.Stream<_i10.QueueUpdate>.empty(),
          )
          as _i6.Stream<_i10.QueueUpdate>);

  @override
  set maxConcurrentDownloads(int? count) => super.noSuchMethod(
    Invocation.setter(#maxConcurrentDownloads, count),
    returnValueForMissingStub: null,
  );

  @override
  set locale(_i4.Locale? value) => super.noSuchMethod(
    Invocation.setter(#locale, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enqueue({
    required String? id,
    required String? url,
    required String? filePath,
    required String? title,
    required String? reciterName,
    int? reciterId,
    bool? showNotification = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #id: id,
              #url: url,
              #filePath: filePath,
              #title: title,
              #reciterName: reciterName,
              #reciterId: reciterId,
              #showNotification: showNotification,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enqueueBatch(
    List<
      ({
        String filePath,
        String id,
        int? reciterId,
        String reciterName,
        bool showNotification,
        String title,
        String url,
      })
    >?
    items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueBatch, [items]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void removeFromQueue(String? id) => super.noSuchMethod(
    Invocation.method(#removeFromQueue, [id]),
    returnValueForMissingStub: null,
  );

  @override
  int getQueuePosition(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuePosition, [id]),
            returnValue: 0,
          )
          as int);

  @override
  bool isQueued(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isQueued, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool isActive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isActive, [id]),
            returnValue: false,
          )
          as bool);

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i11.DownloadService {
  MockDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i12.DownloadProgress> get globalProgressStream =>
      (super.noSuchMethod(
            Invocation.getter(#globalProgressStream),
            returnValue: _i6.Stream<_i12.DownloadProgress>.empty(),
          )
          as _i6.Stream<_i12.DownloadProgress>);

  @override
  _i6.Stream<_i12.DownloadProgress> getProgressStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressStream, [id]),
            returnValue: _i6.Stream<_i12.DownloadProgress>.empty(),
          )
          as _i6.Stream<_i12.DownloadProgress>);

  @override
  _i6.Future<List<String>> getActiveDownloadIds() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveDownloadIds, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> isStatusDownloadActive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isStatusDownloadActive, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i13.DownloadStatus?> getStatus(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, [id]),
            returnValue: _i6.Future<_i13.DownloadStatus?>.value(),
          )
          as _i6.Future<_i13.DownloadStatus?>);

  @override
  _i6.Future<void> download({
    required String? id,
    required String? url,
    required String? filePath,
    required String? title,
    required String? reciterName,
    int? reciterId,
    bool? showNotification = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [], {
              #id: id,
              #url: url,
              #filePath: filePath,
              #title: title,
              #reciterName: reciterName,
              #reciterId: reciterId,
              #showNotification: showNotification,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disposeService() =>
      (super.noSuchMethod(
            Invocation.method(#disposeService, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DownloadNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadNotificationService extends _i1.Mock
    implements _i14.DownloadNotificationService {
  MockDownloadNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> showDownloadProgress({
    required String? downloadId,
    required String? title,
    required String? reciterName,
    required int? progress,
    required _i13.DownloadStatus? status,
    String? pendingMessage,
    String? progressMessage,
    String? completeMessage,
    String? failedMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDownloadProgress, [], {
              #downloadId: downloadId,
              #title: title,
              #reciterName: reciterName,
              #progress: progress,
              #status: status,
              #pendingMessage: pendingMessage,
              #progressMessage: progressMessage,
              #completeMessage: completeMessage,
              #failedMessage: failedMessage,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> showBatchDownloadProgress({
    required String? batchId,
    required String? title,
    required int? progress,
    required int? completedCount,
    required int? totalCount,
    required _i13.DownloadStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showBatchDownloadProgress, [], {
              #batchId: batchId,
              #title: title,
              #progress: progress,
              #completedCount: completedCount,
              #totalCount: totalCount,
              #status: status,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelNotification(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [downloadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> handleNotificationResponse(
    _i15.NotificationResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleNotificationResponse, [response]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DownloadsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsRepository extends _i1.Mock
    implements _i16.DownloadsRepository {
  MockDownloadsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i13.DownloadItem> get downloadUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#downloadUpdates),
            returnValue: _i6.Stream<_i13.DownloadItem>.empty(),
          )
          as _i6.Stream<_i13.DownloadItem>);

  @override
  _i6.Future<void> addDownload(_i13.DownloadItem? downloadItem) =>
      (super.noSuchMethod(
            Invocation.method(#addDownload, [downloadItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDownload(_i13.DownloadItem? downloadItem) =>
      (super.noSuchMethod(
            Invocation.method(#updateDownload, [downloadItem]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownload, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDownloadProgress(
    String? id,
    _i13.DownloadStatus? status,
    double? progress,
    int? downloadedSize,
    int? fileSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDownloadProgress, [
              id,
              status,
              progress,
              downloadedSize,
              fileSize,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> startDownload(
    String? url, {
    required String? title,
    bool? showNotification = true,
    required String? surahTitle,
    required String? reciterName,
    required int? reciterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startDownload,
              [url],
              {
                #title: title,
                #showNotification: showNotification,
                #surahTitle: surahTitle,
                #reciterName: reciterName,
                #reciterId: reciterId,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pauseDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#pauseDownload, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumeDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#resumeDownload, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> retryDownload(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryDownload, [downloadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isSurahDownloaded(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#isSurahDownloaded, [url, reciterName]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isSurahDownloading(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#isSurahDownloading, [url, reciterName]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getDownloadedFilePath(String? url, String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedFilePath, [url, reciterName]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Stream<_i13.DownloadItem> getDownloadProgress(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadProgress, [id]),
            returnValue: _i6.Stream<_i13.DownloadItem>.empty(),
          )
          as _i6.Stream<_i13.DownloadItem>);

  @override
  _i6.Future<void> startDownloadBatch(
    List<({int reciterId, String reciterName, String surahTitle, String url})>?
    items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startDownloadBatch, [items]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelDownloadsForReciter(String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownloadsForReciter, [reciterName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteDownloadsForReciter(String? reciterName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadsForReciter, [reciterName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, Map<String, List<_i13.DownloadItem>>>>
  getDownloadsByReciter() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsByReciter, []),
            returnValue:
                _i6.Future<
                  Map<String, Map<String, List<_i13.DownloadItem>>>
                >.value(<String, Map<String, List<_i13.DownloadItem>>>{}),
          )
          as _i6.Future<Map<String, Map<String, List<_i13.DownloadItem>>>>);

  @override
  _i6.Future<List<_i13.DownloadItem>> getDownloadsForReciter(
    String? reciterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsForReciter, [reciterName]),
            returnValue: _i6.Future<List<_i13.DownloadItem>>.value(
              <_i13.DownloadItem>[],
            ),
          )
          as _i6.Future<List<_i13.DownloadItem>>);

  @override
  _i6.Future<_i13.DownloadItem?> getDownloadItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadItem, [id]),
            returnValue: _i6.Future<_i13.DownloadItem?>.value(),
          )
          as _i6.Future<_i13.DownloadItem?>);

  @override
  _i6.Future<List<_i13.DownloadItem>> getValidCompletedDownloads(
    String? reciterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getValidCompletedDownloads, [reciterName]),
            returnValue: _i6.Future<List<_i13.DownloadItem>>.value(
              <_i13.DownloadItem>[],
            ),
          )
          as _i6.Future<List<_i13.DownloadItem>>);

  @override
  _i6.Future<bool> validateDownloadedFile(_i13.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#validateDownloadedFile, [download]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i5.MediaItem createMediaItemFromDownload(_i13.DownloadItem? download) =>
      (super.noSuchMethod(
            Invocation.method(#createMediaItemFromDownload, [download]),
            returnValue: _FakeMediaItem_3(
              this,
              Invocation.method(#createMediaItemFromDownload, [download]),
            ),
          )
          as _i5.MediaItem);

  @override
  List<_i5.MediaItem> createMediaItemsFromDownloads(
    List<_i13.DownloadItem>? downloads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMediaItemsFromDownloads, [downloads]),
            returnValue: <_i5.MediaItem>[],
          )
          as List<_i5.MediaItem>);

  @override
  _i6.Future<int> getTotalDownloadsSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalDownloadsSize, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> clearAllDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllDownloads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumePendingDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#resumePendingDownloads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
