// Mocks generated by Mockito 5.4.6 from annotations
// in muzakri/test/features/downloads/presentation/widgets/download_item_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hydrated_bloc/hydrated_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:muzakri/features/audio_player/presentation/bloc/audio_player_bloc.dart'
    as _i3;
import 'package:muzakri/features/downloads/data/services/download_queue_manager.dart'
    as _i9;
import 'package:muzakri/features/downloads/data/services/download_service.dart'
    as _i6;
import 'package:muzakri/features/downloads/domain/entities/download_item.dart'
    as _i10;
import 'package:muzakri/features/downloads/presentation/bloc/downloads_bloc.dart'
    as _i2;
import 'package:muzakri/features/downloads/presentation/bloc/downloads_status.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDownloadsState_0 extends _i1.SmartFake
    implements _i2.DownloadsState {
  _FakeDownloadsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioPlayerState_1 extends _i1.SmartFake
    implements _i3.AudioPlayerState {
  _FakeAudioPlayerState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsBloc extends _i1.Mock implements _i2.DownloadsBloc {
  MockDownloadsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.DownloadsStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i4.Stream<_i5.DownloadsStatus>.empty(),
          )
          as _i4.Stream<_i5.DownloadsStatus>);

  @override
  _i4.Stream<_i6.DownloadProgress> get downloadProgressStream =>
      (super.noSuchMethod(
            Invocation.getter(#downloadProgressStream),
            returnValue: _i4.Stream<_i6.DownloadProgress>.empty(),
          )
          as _i4.Stream<_i6.DownloadProgress>);

  @override
  _i2.DownloadsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDownloadsState_0(this, Invocation.getter(#state)),
          )
          as _i2.DownloadsState);

  @override
  _i4.Stream<_i2.DownloadsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.DownloadsState>.empty(),
          )
          as _i4.Stream<_i2.DownloadsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i4.Stream<_i6.DownloadProgress> getDownloadProgressStream(
    String? downloadId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadProgressStream, [downloadId]),
            returnValue: _i4.Stream<_i6.DownloadProgress>.empty(),
          )
          as _i4.Stream<_i6.DownloadProgress>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.DownloadsState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i2.DownloadsState?);

  @override
  Map<String, dynamic>? toJson(_i2.DownloadsState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i2.DownloadsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.DownloadsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.DownloadsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.DownloadsEvent>(
    _i8.EventHandler<E, _i2.DownloadsState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i2.DownloadsEvent, _i2.DownloadsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i2.DownloadsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i2.DownloadsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i8.Storage? storage,
    _i8.OnHydrationError? onError = _i8.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AudioPlayerBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerBloc extends _i1.Mock implements _i3.AudioPlayerBloc {
  MockAudioPlayerBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioPlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAudioPlayerState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AudioPlayerState);

  @override
  _i4.Stream<_i3.AudioPlayerState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i3.AudioPlayerState>.empty(),
          )
          as _i4.Stream<_i3.AudioPlayerState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i3.AudioPlayerState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i3.AudioPlayerState?);

  @override
  Map<String, dynamic>? toJson(_i3.AudioPlayerState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i3.AudioPlayerEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AudioPlayerEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AudioPlayerState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AudioPlayerEvent>(
    _i8.EventHandler<E, _i3.AudioPlayerState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i3.AudioPlayerEvent, _i3.AudioPlayerState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.AudioPlayerEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onChange(_i8.Change<_i3.AudioPlayerState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i8.Storage? storage,
    _i8.OnHydrationError? onError = _i8.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DownloadQueueManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadQueueManager extends _i1.Mock
    implements _i9.DownloadQueueManager {
  MockDownloadQueueManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get maxConcurrentDownloads =>
      (super.noSuchMethod(
            Invocation.getter(#maxConcurrentDownloads),
            returnValue: 0,
          )
          as int);

  @override
  int get queueLength =>
      (super.noSuchMethod(Invocation.getter(#queueLength), returnValue: 0)
          as int);

  @override
  int get activeDownloadsCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeDownloadsCount),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Stream<_i9.QueueUpdate> get queueUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#queueUpdates),
            returnValue: _i4.Stream<_i9.QueueUpdate>.empty(),
          )
          as _i4.Stream<_i9.QueueUpdate>);

  @override
  void setMaxConcurrentDownloads(int? count) => super.noSuchMethod(
    Invocation.method(#setMaxConcurrentDownloads, [count]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> enqueue({
    required String? id,
    required String? url,
    required String? filePath,
    required String? title,
    required String? reciterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #id: id,
              #url: url,
              #filePath: filePath,
              #title: title,
              #reciterName: reciterName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void removeFromQueue(String? id) => super.noSuchMethod(
    Invocation.method(#removeFromQueue, [id]),
    returnValueForMissingStub: null,
  );

  @override
  int getQueuePosition(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuePosition, [id]),
            returnValue: 0,
          )
          as int);

  @override
  bool isQueued(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isQueued, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool isActive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isActive, [id]),
            returnValue: false,
          )
          as bool);

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i6.DownloadService {
  MockDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> download({
    required String? id,
    required String? url,
    required String? filePath,
    required String? title,
    required String? reciterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [], {
              #id: id,
              #url: url,
              #filePath: filePath,
              #title: title,
              #reciterName: reciterName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i6.DownloadProgress> getProgressStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressStream, [id]),
            returnValue: _i4.Stream<_i6.DownloadProgress>.empty(),
          )
          as _i4.Stream<_i6.DownloadProgress>);

  @override
  _i4.Future<List<String>> getActiveDownloadIds() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveDownloadIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> isStatusDownloadActive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isStatusDownloadActive, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i10.DownloadStatus?> getStatus(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, [id]),
            returnValue: _i4.Future<_i10.DownloadStatus?>.value(),
          )
          as _i4.Future<_i10.DownloadStatus?>);

  @override
  _i4.Future<void> disposeService() =>
      (super.noSuchMethod(
            Invocation.method(#disposeService, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
